# coding: utf-8

"""
    TDC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tdc_api_client.api.expenses_api import ExpensesApi


class TestExpensesApi(unittest.TestCase):
    """ExpensesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExpensesApi()

    def tearDown(self) -> None:
        pass

    def test_get_expenses_expense_id_get(self) -> None:
        """Test case for get_expenses_expense_id_get

        Get
        """
        pass

    def test_get_expenses_get(self) -> None:
        """Test case for get_expenses_get

        Get
        """
        pass

    def test_get_project_expenses_project_id_expenses_get(self) -> None:
        """Test case for get_project_expenses_project_id_expenses_get

        Get Project
        """
        pass

    def test_post_expenses_post(self) -> None:
        """Test case for post_expenses_post

        Post
        """
        pass


if __name__ == '__main__':
    unittest.main()
