# coding: utf-8

"""
    TDC API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from tdc_api_client.models.expense import Expense

class TestExpense(unittest.TestCase):
    """Expense unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Expense:
        """Test Expense
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Expense`
        """
        model = Expense()
        if include_optional:
            return Expense(
                id = '',
                project = tdc_api_client.models.project.Project(
                    id = '', 
                    name = '', 
                    description = '', ),
                caption = '',
                amount = 1.337,
                date_ = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                needs_refund = True,
                refunded = True,
                date_refund = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return Expense(
                id = '',
                project = tdc_api_client.models.project.Project(
                    id = '', 
                    name = '', 
                    description = '', ),
                caption = '',
                amount = 1.337,
                date_ = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testExpense(self):
        """Test Expense"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
