# coding: utf-8

"""
    TDC Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tdc_api_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_get_projects_expense_id_get(self) -> None:
        """Test case for get_projects_expense_id_get

        Get
        """
        pass

    def test_get_projects_get(self) -> None:
        """Test case for get_projects_get

        Get
        """
        pass

    def test_post_projects_post(self) -> None:
        """Test case for post_projects_post

        Post
        """
        pass


if __name__ == '__main__':
    unittest.main()
