# coding: utf-8

"""
    TDC Web API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tdc_api_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_post_expense_expenses_post(self) -> None:
        """Test case for post_expense_expenses_post

        Post Expense
        """
        pass

    def test_read_expenses_expenses_expense_id_get(self) -> None:
        """Test case for read_expenses_expenses_expense_id_get

        Read Expenses
        """
        pass

    def test_read_expenses_expenses_get(self) -> None:
        """Test case for read_expenses_expenses_get

        Read Expenses
        """
        pass


if __name__ == '__main__':
    unittest.main()
